apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2h6h
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tsep-tenant/rhtap-demo-app/hacbs-test-project-2h6h@sha256:815b546bd9b34deda16c1477568e8872b94853390b009b3c5a2d5b34be008309
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
