apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2h6h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2h6h
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2h6h
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2h6h
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2h6h
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tsep-tenant/rhtap-demo-app/hacbs-test-project-2h6h@sha256:815b546bd9b34deda16c1477568e8872b94853390b009b3c5a2d5b34be008309
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
